### ISSUE TITLE
Allow output customization by exposing ITextFormatter

### ISSUE THREAD

**Issue by cecilphillip** [serilog/serilog-sinks-opentelemetry#82]
Adding on to the discussion started here..
https://github.com/serilog/serilog-sinks-opentelemetry/pull/43#issuecomment-1527079960.

Currently using the otel-collector to distribute telemetry to various endpoints.  Using the code similar to the following
```csharp
 .Enrich.WithEnvironmentName()
 .Enrich.WithMachineName()
 .WriteTo.OpenTelemetry(opts =>
    {
        opts.ResourceAttributes = new Dictionary<string, object>
        {
            ["app"] = "web",
            ["runtime"] = "dotnet",
            ["service.name"] = "MainService",
            ["logger"] = "OLTP"
        };
    })
``` 
It comes out looking like this by default.

![Screenshot 2023-05-16 at 12 37 35 PM](https://github.com/serilog/serilog-sinks-opentelemetry/assets/350882/9e148a59-a56b-4cdd-9a2d-a6914b879570)

We'd love to condense the stored log record to look more like this

![Screenshot 2023-05-16 at 12 38 17 PM](https://github.com/serilog/serilog-sinks-opentelemetry/assets/350882/cc328da5-e678-4ff3-8664-a07a3d3b603d)

The above screenshot is using a different Sink with a custom ITextFormatter, but it doesn't go through OpenTelemetry.

It would be helpful to have the option to configure log formatting for this Serilog.Sinks.OpenTelemetry

**Comment by nblumhardt** [comment]
Interesting - thanks for the heads-up, @cecilphillip.

Open to making whatever improvements are needed here, but I think that your situation is a collector configuration problem - what's happening is that the OTLP message from Serilog is being wrapped by the collector inside another message, somehow, before forwarding onto Loki.

That big JSON structure is actually the whole original payload, reformatted. It's quite different from how OTLP logging payloads look today, though, so my best guess is that the collector's using an early version of the protocol, or something along those lines?

@loomis has more experience with the collector than I do, so might be able to spot what's going on, htere.

**Comment by loomis** [comment]
@cecilphillip Can you post your collector configuration and which version of the collector you're using?

**Comment by cecilphillip** [comment]
@nblumhardt yea, I think you're right. Looks like it's something in the collector connfig. I tried a different Otel logger and got a similar payload.

@loomis  here's my config
docker-compose
```yaml
  otel-collector:
    container_name: otelcollector
    image: otel/opentelemetry-collector-contrib:0.73.0
    command: [ --config=/etc/otel-collector-config.yml ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
```

Collector config
```yaml
receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ loki ]

```

**Comment by loomis** [comment]
@cecilphillip I'll try to run the full data flow tomorrow. In the meantime, you might want to add this to the collector configuration:

```yaml
exporters:
  logging:
    verbosity: detailed
```

and then update the pipeline configuration with:

```yaml
exporters: [ logging, loki ]
```

You can then tail the logs on the collector image to see the full OpenTelemetry log payload. This will let you see whether some strange refactoring is happening within the collector. 

You should probably also update to the latest image version: `otel/opentelemetry-collector-contrib:0.77.0`. This isn't the cause of your problems, but it is always better to use the latest one.

**Comment by cecilphillip** [comment]
@loomis  I fixed it! Need to add this attribute to the collector config

```yaml
processors:
    attributes:
      - action: insert
        key: loki.format
        value: raw
```
